---
title: C28125 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 6
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: bd9a17d781ba106e20512aaff1c46ba0952cb9cf
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/15/2020
ms.locfileid: "77265752"
---
# <a name="c28125"></a>C28125
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

aviso C28125: a função deve ser chamada de dentro de um bloco try/Except  
  
 O driver está chamando uma função que deve ser chamada de dentro de um bloco try/Except, como [ProbeForRead](https://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](https://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](https://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## <a name="example"></a>{1&gt;Exemplo&lt;1}  
 O exemplo de código a seguir gera este aviso:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 O exemplo de código a seguir evita esse aviso:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```
