---
title: C6320 | Microsoft Docs
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: cffb779f2b92cfee495480e2a1ba4946c5def605
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 11/16/2018
ms.locfileid: "51798112"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Aviso C6320: a expressão de filtro de exceção é a constante EXCEPTION_EXECUTE_HANDLER. Isso pode mascarar exceções que não foram feitas para serem tratadas  
  
 Este aviso indica que o efeito colateral de usar a constante EXCEPTION_EXECUTE_HANDLER, no bloco EXCEPT. Nesse caso, a instrução no \_bloco EXCEPT sempre será executado para lidar com a exceção, incluindo as exceções que você não quiser lidar com uma função específica. É recomendável que você verifique a exceção antes de lidar com isso.  
  
## <a name="example"></a>Exemplo  
 O código a seguir gera este aviso, pois o __except bloco tentar tratar exceções de todos os tipos:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Para corrigir este aviso, use `GetExceptionCode` para verificar se há uma exceção específica antes de lidar com isso, conforme mostrado no código a seguir:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Consulte também  
 [Instrução try-except](http://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)



