---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: a0e91d4d8fedae14a23ed118ab592fe0842a27e8
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 10/07/2019
ms.locfileid: "72015666"
---
# <a name="c26111"></a>C26111
C26111 de aviso: Falha do chamador ao liberar o bloqueio \<lock > antes de chamar a função \<func >.

 A anotação `_Requires_lock_not_held_` impõe uma pré-condição de que a contagem de bloqueios para o bloqueio especificado não pode ser maior que zero quando a função é chamada. Aviso C26111 é emitido quando uma função não libera o bloqueio antes de chamar outra função.

## <a name="example"></a>Exemplo
 O exemplo a seguir gera C26111 de aviso porque a pré-condição `_Requires_lock_not_held_` é violada pela chamada para `DoNotLock` na seção bloqueada.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```