---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: c0906c1e876a13049dfe1d1e7727c22528f8e8ed
ms.sourcegitcommit: 21d667104199c2493accec20c2388cf674b195c3
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/08/2019
ms.locfileid: "55946087"
---
# <a name="c28105"></a>C28105
Warning C28105: Vazamento de recursos devido a uma exceção

 O recurso especificado não é liberado quando uma exceção é gerada. A instrução especificada pelo caminho poderá gerar uma exceção. Esse aviso é semelhante ao aviso [C28103](../code-quality/c28103.md), exceto que, nesse caso, uma exceção está envolvida.

## <a name="example"></a>Exemplo
 O exemplo de código a seguir gera este aviso:

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 O exemplo de código a seguir evita este aviso:

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```